
on:
  push:
    branches:
    - '*'
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: "Install Dependencies"
        run: |
          echo ${{secrets.npmAuth}} >> ~/.npmrc
          yarn --frozen-lockfile
      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1
        with:
          api-key: 8229158d3befa3c8ee0db34e3714e394
      - name: create PR
        if: ${{ success() }}   
        uses: peter-evans/create-pull-request@v3   
